### PR TITLE
Add additional values: 'deploymentAnnotations', 'args', 'command'

### PR DESCRIPTION
**Pull request by LanceSandino**
Added additional values for the deployment.

You can now add `annotations` like the chart allows under `pods`

And the `args` and `command` for things like sourcing an environmental file from a vault container prior to running the application.

### CODE REVIEW

**Comment by echoboomer** [comment]
@LanceSandino would you mind bumping the chart version as part of this? That way when it's merged it will automatically build and push that version and you can begin using it immediately.

**Review by echoboomer — CHANGES_REQUESTED** [review]
Bumping the chart version is the only other required change.

**Comment by LanceSandino** [comment]
For sure! I didn’t know how it got bumped but if the image builds that’s
great! --
Thanks,

Lance Sandino

**Comment by LanceSandino** [comment]
Bumped the chart version :)

**Pull request merged**
